language: python

install:
  - pip install py-bcrypt libnacl

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - libsodium
      python: 3.4
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - libsodium
      python: 3.5
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - libsodium
      python: nightly
    - os: osx
      osx_image: xcode7.3
      language: generic
      before_install:
        - brew update
        - brew install python3
        - virtualenv venv -p python3
        - source venv/bin/activate

script: ./setup.py test
