language: python

install:
  - pip install tox py-bcrypt libnacl

matrix:
  allow_failures:
    - python: nightly
  fast_finish: true
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: 3.4
      before_install:
        - .travis/build-libsodium.sh
      env:
        - TOXENV=py34
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
      before_install:
        - .travis/build-libsodium.sh
      env:
        - TOXENV=py35
    - os: linux
      sudo: required
      dist: trusty
      python: nightly
      before_install:
        - .travis/build-libsodium.sh
      env:
        - TOXENV=py36
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - CPPFLAGS=-I/usr/local/opt/openssl/include
        - LDFLAGS=-L/usr/local/opt/openssl/lib -L/usr/local/opt/libffi/lib
        - PYENV_ROOT=.pyenv
        - TOXENV=py34
      before_install:
        - brew update
        - brew install libffi libsodium openssl pyenv pyenv-virtualenv
        - pyenv install 3.4.4
        - pyenv global 3.4.4
        - pyenv-virtualenv venv
        - source venv/bin/activate
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - CPPFLAGS=-I/usr/local/opt/openssl/include
        - LDFLAGS=-L/usr/local/opt/openssl/lib -L/usr/local/opt/libffi/lib
        - TOXENV=py35
      before_install:
        - brew update
        - brew install libffi libsodium openssl pyenv pyenv-virtualenv
        - pyenv install 3.5.1
        - pyenv global 3.5.1
        - pyenv-virtualenv venv
        - source venv/bin/activate

script: tox
