language:
  - python

install:
  - .travis/install.sh

script:
  - export PATH="/usr/local/opt/openssl/bin:$PATH"
  - export PATH="$HOME/.pyenv/shims:$HOME/.pyenv/bin:$PATH"
  - travis_wait 60 tox

matrix:
  allow_failures:
    - python: nightly
    - env: PYENV_VERSION=3.7-dev TOXENV=py37
    - env: PYENV_VERSION=3.7-dev TOXENV=py37 USE_UVLOOP=1
  fast_finish: true
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: 3.4
      env: TOXENV=py34
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
      env: TOXENV=py35
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
      env: TOXENV=py35 USE_UVLOOP=1
    - os: linux
      sudo: required
      dist: trusty
      python: 3.6
      env: TOXENV=py36
    - os: linux
      sudo: required
      dist: trusty
      python: 3.6
      env: TOXENV=py36 USE_UVLOOP=1
    - os: linux
      sudo: required
      dist: trusty
      python: nightly
      env: TOXENV=py37
    - os: linux
      sudo: required
      dist: trusty
      python: nightly
      env: TOXENV=py37 USE_UVLOOP=1
    - os: osx
      osx_image: xcode9.1
      language: generic
      env: PYENV_VERSION=3.4-dev TOXENV=py34
    - os: osx
      osx_image: xcode9.1
      language: generic
      env: PYENV_VERSION=3.5-dev TOXENV=py35
    - os: osx
      osx_image: xcode9.1
      language: generic
      env: PYENV_VERSION=3.5-dev TOXENV=py35 USE_UVLOOP=1
    - os: osx
      osx_image: xcode9.1
      language: generic
      env: PYENV_VERSION=3.6-dev TOXENV=py36
    - os: osx
      osx_image: xcode9.1
      language: generic
      env: PYENV_VERSION=3.6-dev TOXENV=py36 USE_UVLOOP=1
    - os: osx
      osx_image: xcode9.1
      language: generic
      env: PYENV_VERSION=3.7-dev TOXENV=py37
    - os: osx
      osx_image: xcode9.1
      language: generic
      env: PYENV_VERSION=3.7-dev TOXENV=py37 USE_UVLOOP=1
