language: python

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: 3.4
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
    - os: linux
      sudo: required
      dist: trusty
      python: nightly
    - os: osx
      osx_image: xcode7.3
      python: 3.4

script: ./setup.py test
