language: python

install:
  - pip install py-bcrypt libnacl

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: 3.4
      before_install:
        - .travis/build-libsodium.sh
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
      before_install:
        - .travis/build-libsodium.sh
    - os: linux
      sudo: required
      dist: trusty
      python: nightly
      before_install:
        - .travis/build-libsodium.sh
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - CPPFLAGS=-I/usr/local/opt/openssl/include
        - LDFLAGS=-L/usr/local/opt/openssl/lib -L/usr/local/opt/libffi/lib
      before_install:
        - brew update
        - brew install libffi libsodium openssl python3
        - pip install virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate

script: python3 ./setup.py test
