language: python

install:
  - pip install py-bcrypt libnacl

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: 3.4
    - os: linux
      sudo: required
      dist: trusty
      python: 3.5
    - os: linux
      sudo: required
      dist: trusty
      python: nightly
    - os: osx
      osx_image: xcode7.3
      language: generic
      before_install:
        - brew update
        - brew install libsodium openssl python3
        - pip3 install virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate

script: python3 ./setup.py test
