environment:
  matrix:
    - PYTHON: "C:\\Python34"
      ARCH: win32

    - PYTHON: "C:\\Python34-x64"
      ARCH: win64

    - PYTHON: "C:\\Python35"
      ARCH: win32

    - PYTHON: "C:\\Python35-x64"
      ARCH: win64

    - PYTHON: "C:\\Python36"
      ARCH: win32

    - PYTHON: "C:\\Python36-x64"
      ARCH: win64

install:
  - "cd %PYTHON%"
  - "curl https://www.timeheart.net/appveyor/%ARCH%/libsodium-18.dll -O"
  - "curl https://www.timeheart.net/appveyor/%ARCH%/libnettle-6.dll -O"
  - "curl https://www.timeheart.net/appveyor/%ARCH%/libhogweed-4.dll -O"
  - "cd %APPVEYOR_BUILD_FOLDER%"
  - "%PYTHON%\\python.exe -m pip install bcrypt libnacl pypiwin32 tox"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -e py"
